export declare const onLeadCreated: any;
export declare const onLeadUpdated: any;
export declare const onLeadDeleted: any;
export declare const onStatusUpdateCreated: any;
export declare const onTeamUpdated: any;
export declare const onTeamDeleted: any;
export declare const onReminderCreated: any;
export declare const onReminderStatusChanged: any;
export declare const onUserUpdated: any;
